[package]
name = "yaml-rust2"
version = "0.11.0"
authors = [
  "Yuheng Chen <yuhengchen@sensetime.com>",
  "Ethiraric <ethiraric@gmail.com>",
  "David Aguilar <davvid@gmail.com>"
]
documentation = "https://docs.rs/yaml-rust2"
license = "MIT OR Apache-2.0"
description = "A fully YAML 1.2 compliant YAML parser"
repository = "https://github.com/Ethiraric/yaml-rust2"
readme = "README.md"
edition = "2021"
rust-version = "1.65.0"
exclude = [
  # We don't need the documents either.
  "/documents",
  # Exclude the `yaml-test-suite` from the package. This removes the need to
  # add its license to the package.
  "/tests/yaml-test-suite"
]

[features]
default = [ "encoding" ]
debug_prints = []
encoding = [ "dep:encoding_rs" ]
# YAML 1.1 compatibility: treat leading-zero integers as octal (0644 = 420)
yaml-1-1 = []

[dependencies]
arraydeque = "0.5.1"
encoding_rs = { version = "0.8.33", optional = true }
hashlink = "0.11"

[dev-dependencies]
libtest-mimic = "0.8"
quickcheck = "1.0"

[profile.release-lto]
inherits = "release"
lto = true

[[test]]
name = "yaml-test-suite"
harness = false

[[example]]
name = "dump_events"
path = "tools/dump_events.rs"

[[example]]
name = "time_parse"
path = "tools/time_parse.rs"

[[example]]
name = "run_bench"
path = "tools/run_bench.rs"
